//
// DO NOT MODIFY version.hpp, it is automatically generated by cmake
// MODIFY version.hpp.in as needed
//

#ifndef SZ3_VERSION_HPP
#define SZ3_VERSION_HPP

#define PROJECT_NAME "SZ3"
#define PROJECT_VER  "3.1.3.0"
#define PROJECT_VER_MAJOR "3"
#define PROJECT_VER_MINOR "1"
#define PTOJECT_VER_PATCH "3"
#define PTOJECT_VER_TWEAK "0"

#endif //SZ3_VERSION_HPP
